spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

kafka:
  topics:
    replication-factor: ${KAFKA_TOPIC_REPLICATION_FACTOR:3}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
